/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.bundesbank.transreg.options;

import static de.bundesbank.transreg.options.TransRegOptionsPanelController.*;
import org.openide.util.NbPreferences;

final class TransRegPanel extends javax.swing.JPanel {

    private final TransRegOptionsPanelController controller;

    TransRegPanel(TransRegOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        saveMethodComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maxNumberOfVerticalGroupsComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maxNumberOfHorizontalGroupsComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        upperLimitExpField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lowerLimitExpField = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel2.text")); // NOI18N
        jPanel1.add(jLabel2);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel13.text")); // NOI18N
        jPanel1.add(jLabel13);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel1);

        saveMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(SaveMethodEnum.values()));
        jPanel1.add(saveMethodComboBox);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel6.text")); // NOI18N
        jPanel2.add(jLabel6);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel4.text")); // NOI18N
        jPanel2.add(jLabel4);

        maxNumberOfVerticalGroupsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel2.add(maxNumberOfVerticalGroupsComboBox);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel14.text")); // NOI18N
        jPanel2.add(jLabel14);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel15.text")); // NOI18N
        jPanel2.add(jLabel15);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel5.text")); // NOI18N
        jPanel2.add(jLabel5);

        maxNumberOfHorizontalGroupsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "19", "11", "12" }));
        jPanel2.add(maxNumberOfHorizontalGroupsComboBox);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel7.text")); // NOI18N
        jPanel3.add(jLabel7);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel10.text")); // NOI18N
        jPanel3.add(jLabel10);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel8.text")); // NOI18N
        jPanel3.add(jLabel8);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel11.text")); // NOI18N
        jPanel4.add(jLabel11);

        upperLimitExpField.setText(org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.upperLimitExpField.text")); // NOI18N
        jPanel4.add(upperLimitExpField);

        jPanel3.add(jPanel4);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel9.text")); // NOI18N
        jPanel3.add(jLabel9);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.jLabel12.text")); // NOI18N
        jPanel5.add(jLabel12);

        lowerLimitExpField.setText(org.openide.util.NbBundle.getMessage(TransRegPanel.class, "TransRegPanel.lowerLimitExpField.text")); // NOI18N
        jPanel5.add(lowerLimitExpField);

        jPanel3.add(jPanel5);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        String saveMethod = NbPreferences.forModule(TransRegOptionsPanelController.class).get(TRANSREG_SAVE_METHOD, SaveMethodEnum.NONE.toString());
        saveMethodComboBox.setSelectedItem(SaveMethodEnum.fromString(saveMethod));

        int nr_v = NbPreferences.forModule(TransRegOptionsPanelController.class).getInt(TRANSREG_VERTICAL_GROUPS, 2);
        maxNumberOfVerticalGroupsComboBox.setSelectedItem(nr_v-2);

        int nr_h = NbPreferences.forModule(TransRegOptionsPanelController.class).getInt(TRANSREG_HORIZONTAL_GROUPS, 2);
        maxNumberOfHorizontalGroupsComboBox.setSelectedItem(nr_h-2);

        double upper = NbPreferences.forModule(TransRegOptionsPanelController.class).getDouble(TRANSREG_UPPER_LIMIT, Math.pow(10, -4));
        
        upperLimitExpField.setText(Math.log10(upper)+"");

        double lower = NbPreferences.forModule(TransRegOptionsPanelController.class).getDouble(TRANSREG_LOWER_LIMIT, Math.pow(10, -12));
        lowerLimitExpField.setText(Math.log10(lower)+"");
    }

    void store() {

        // SaveMethodEnum
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                put(TRANSREG_SAVE_METHOD, 
                        saveMethodComboBox.getSelectedItem().toString()
                );
        
        // Number of groups, vertical
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putInt(TRANSREG_VERTICAL_GROUPS, 
                        Integer.parseInt(maxNumberOfVerticalGroupsComboBox.getSelectedItem().toString())
                );
        
        // Number of groups, horizontal
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putInt(TRANSREG_HORIZONTAL_GROUPS, 
                        Integer.parseInt( maxNumberOfHorizontalGroupsComboBox.getSelectedItem().toString())
                );
        
        // Try catch block wegen parsen?
        // upper limit exponent 
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putDouble(TRANSREG_UPPER_LIMIT, 
                        Math.pow(10, Double.parseDouble(upperLimitExpField.getText()))
                );
        
        // lower limit exponent
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putDouble(TRANSREG_LOWER_LIMIT, 
                        Math.pow(10, Double.parseDouble(lowerLimitExpField.getText()))
                );
    }

    boolean valid() {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lowerLimitExpField;
    private javax.swing.JComboBox maxNumberOfHorizontalGroupsComboBox;
    private javax.swing.JComboBox maxNumberOfVerticalGroupsComboBox;
    private javax.swing.JComboBox saveMethodComboBox;
    private javax.swing.JTextField upperLimitExpField;
    // End of variables declaration//GEN-END:variables
}
