/* 
 * Copyright 2018 Deutsche Bundesbank
 * 
 * Licensed under the EUPL, Version 1.1 or – as soon they
 * will be approved by the European Commission - subsequent 
 * versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the
 * Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl.html
 * 
 * Unless required by applicable law or agreed to in
 * writing, software distributed under the Licence is
 * distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied.
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
 */
package de.bundesbank.transreg.options;

import static de.bundesbank.transreg.options.TransRegOptionsPanelController.*;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.openide.util.NbPreferences;

final class TransRegOptionPanel extends javax.swing.JPanel implements ChangeListener {

    private final TransRegOptionsPanelController controller;

    TransRegOptionPanel(TransRegOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
        upperSpinner.addChangeListener(this);
        lowerSpinner.addChangeListener(this);
        
        ((JSpinner.DefaultEditor)upperSpinner.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor)lowerSpinner.getEditor()).getTextField().setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        maxNumberOfGroupsComboBox = new javax.swing.JComboBox();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        upperSpinner = new javax.swing.JSpinner();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        lowerSpinner = new javax.swing.JSpinner();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        warning = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel1.text")); // NOI18N

        setLayout(new java.awt.GridLayout(4, 1));

        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel6.text")); // NOI18N
        jPanel2.add(jLabel6);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel4.text")); // NOI18N
        jPanel2.add(jLabel4);

        maxNumberOfGroupsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel2.add(maxNumberOfGroupsComboBox);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel14.text")); // NOI18N
        jPanel2.add(jLabel14);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel15.text")); // NOI18N
        jPanel2.add(jLabel15);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel7.text")); // NOI18N
        jPanel3.add(jLabel7);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel10.text")); // NOI18N
        jPanel3.add(jLabel10);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel8.text")); // NOI18N
        jPanel3.add(jLabel8);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel11.text")); // NOI18N
        jPanel4.add(jLabel11);

        upperSpinner.setModel(new javax.swing.SpinnerNumberModel(4, 0, 99, 1));
        upperSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(upperSpinner, ""));
        jPanel4.add(upperSpinner);

        jPanel3.add(jPanel4);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel9.text")); // NOI18N
        jPanel3.add(jLabel9);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel12.text")); // NOI18N
        jPanel5.add(jLabel12);

        lowerSpinner.setModel(new javax.swing.SpinnerNumberModel(12, 1, 100, 1));
        lowerSpinner.setToolTipText(org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.lowerSpinner.toolTipText")); // NOI18N
        lowerSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lowerSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(lowerSpinner, ""));
        jPanel5.add(lowerSpinner);

        jPanel3.add(jPanel5);

        add(jPanel3);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        warning.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        warning.setForeground(new java.awt.Color(255, 0, 0));
        org.openide.awt.Mnemonics.setLocalizedText(warning, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.warning.text")); // NOI18N
        jPanel1.add(warning);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    void load() {

        int nr_v = NbPreferences.forModule(TransRegOptionsPanelController.class).getInt(TRANSREG_GROUPS, 2);
        maxNumberOfGroupsComboBox.setSelectedItem(nr_v - 2);

//        int nr_h = NbPreferences.forModule(TransRegOptionsPanelController.class).getInt(TRANSREG_HORIZONTAL_GROUPS, 2);
//        maxNumberOfHorizontalGroupsComboBox.setSelectedItem(nr_h-2);
        double upper = NbPreferences.forModule(TransRegOptionsPanelController.class).getDouble(TRANSREG_UPPER_LIMIT, 1E-4);
        int u = -1 * (int) Math.log10(upper);
        upperSpinner.setValue(u);

        double lower = NbPreferences.forModule(TransRegOptionsPanelController.class).getDouble(TRANSREG_LOWER_LIMIT, 1E-12);
        int l = -1 * (int) Math.log10(lower);
        lowerSpinner.setValue(l);
    }

    void store() {

        // Number of groups
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putInt(TRANSREG_GROUPS,
                        Integer.parseInt(maxNumberOfGroupsComboBox.getSelectedItem().toString())
                );

        // Tresholds
        int u = ((SpinnerNumberModel) upperSpinner.getModel()).getNumber().intValue();
        double upper = Math.pow(10, -u);
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putDouble(TRANSREG_UPPER_LIMIT, upper);

        int l = ((SpinnerNumberModel) lowerSpinner.getModel()).getNumber().intValue();
        double lower = Math.pow(10, -l);
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putDouble(TRANSREG_LOWER_LIMIT, lower);

    }

    boolean valid() {
        int upper = ((SpinnerNumberModel) upperSpinner.getModel()).getNumber().intValue();
        int lower = ((SpinnerNumberModel) lowerSpinner.getModel()).getNumber().intValue();

        if (lower > upper) {
            warning.setText("");
            return true;
        }
        if (lower == upper) {
            warning.setText(WARNING_TEXT_EQUALS);
            return false;
        }
        warning.setText(WARNING_TEXT_SMALLER);
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner lowerSpinner;
    private javax.swing.JComboBox maxNumberOfGroupsComboBox;
    private javax.swing.JSpinner upperSpinner;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables

    private static final String WARNING_TEXT_SMALLER = "WARNING: Upper treshold is smaller than lower.";
    private static final String WARNING_TEXT_EQUALS = "WARNING: Lower treshold is not smaller than upper.";

    @Override
    public void stateChanged(ChangeEvent e) {
        controller.changed();
    }
}
