/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.bundesbank.transreg.options;

import static de.bundesbank.transreg.options.TransRegOptionsPanelController.*;
import org.openide.util.NbPreferences;

final class TransRegOptionPanel extends javax.swing.JPanel {

    private final TransRegOptionsPanelController controller;

    TransRegOptionPanel(TransRegOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maxNumberOfGroupsComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        upperLimitExpField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lowerLimitExpField = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(3, 1));

        jPanel2.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel3.text")); // NOI18N
        jPanel2.add(jLabel3);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel6.text")); // NOI18N
        jPanel2.add(jLabel6);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel4.text")); // NOI18N
        jPanel2.add(jLabel4);

        maxNumberOfGroupsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel2.add(maxNumberOfGroupsComboBox);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel14.text")); // NOI18N
        jPanel2.add(jLabel14);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel15.text")); // NOI18N
        jPanel2.add(jLabel15);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel7.text")); // NOI18N
        jPanel3.add(jLabel7);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel10.text")); // NOI18N
        jPanel3.add(jLabel10);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel8.text")); // NOI18N
        jPanel3.add(jLabel8);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel11.text")); // NOI18N
        jPanel4.add(jLabel11);

        upperLimitExpField.setText(org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.upperLimitExpField.text")); // NOI18N
        jPanel4.add(upperLimitExpField);

        jPanel3.add(jPanel4);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel9.text")); // NOI18N
        jPanel3.add(jLabel9);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.jLabel12.text")); // NOI18N
        jPanel5.add(jLabel12);

        lowerLimitExpField.setText(org.openide.util.NbBundle.getMessage(TransRegOptionPanel.class, "TransRegOptionPanel.lowerLimitExpField.text")); // NOI18N
        jPanel5.add(lowerLimitExpField);

        jPanel3.add(jPanel5);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        String saveMethod = NbPreferences.forModule(TransRegOptionsPanelController.class).get(TRANSREG_SAVE_METHOD, SaveMethodEnum.TRANSREG.toString());
//        saveMethodComboBox.setSelectedItem(SaveMethodEnum.fromString(saveMethod));

        int nr_v = NbPreferences.forModule(TransRegOptionsPanelController.class).getInt(TRANSREG_GROUPS, 2);
        maxNumberOfGroupsComboBox.setSelectedItem(nr_v-2);

//        int nr_h = NbPreferences.forModule(TransRegOptionsPanelController.class).getInt(TRANSREG_HORIZONTAL_GROUPS, 2);
//        maxNumberOfHorizontalGroupsComboBox.setSelectedItem(nr_h-2);

        double upper = NbPreferences.forModule(TransRegOptionsPanelController.class).getDouble(TRANSREG_UPPER_LIMIT, 1E-4);
        
        upperLimitExpField.setText(((int) Math.log10(upper))+"");

        double lower = NbPreferences.forModule(TransRegOptionsPanelController.class).getDouble(TRANSREG_LOWER_LIMIT, 1E-12);
        lowerLimitExpField.setText(((int) Math.log10(lower))+"");
    }

    void store() {

        // SaveMethodEnum
//        NbPreferences.forModule(TransRegOptionsPanelController.class).
//                put(TRANSREG_SAVE_METHOD, 
//                        saveMethodComboBox.getSelectedItem().toString()
//                );
        
        // Number of groups, vertical
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putInt(TRANSREG_GROUPS, 
                        Integer.parseInt(maxNumberOfGroupsComboBox.getSelectedItem().toString())
                );
        
//        // Number of groups, horizontal
//        NbPreferences.forModule(TransRegOptionsPanelController.class).
//                putInt(TRANSREG_HORIZONTAL_GROUPS, 
//                        Integer.parseInt( maxNumberOfHorizontalGroupsComboBox.getSelectedItem().toString())
//                );
        
        // Try catch block wegen parsen?
        // upper limit exponent 
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putDouble(TRANSREG_UPPER_LIMIT, 
                        Double.parseDouble("1E"+upperLimitExpField.getText())
                );
        
        // lower limit exponent
        NbPreferences.forModule(TransRegOptionsPanelController.class).
                putDouble(TRANSREG_LOWER_LIMIT, 
                        Double.parseDouble("1E"+lowerLimitExpField.getText())
                );
    }

    boolean valid() {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lowerLimitExpField;
    private javax.swing.JComboBox maxNumberOfGroupsComboBox;
    private javax.swing.JTextField upperLimitExpField;
    // End of variables declaration//GEN-END:variables
}
